#baseURL = 'http://localhost'
baseURL = '/'
languageCode = 'en-us'
title = 'KAUotic Hacking Club'
theme = 'hermit'

[author]
    name = "Arcnilya & ChatGPT"

[taxonomies]
    tags = "tags"

# Hermit dateform error fix
[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    description = "KAUotic Hacking Club: a club at Karlstad University about hacking, privacy and security"
    images = ["images/kauotic_logo.png"]

    #themeColor = "#494f5c"
    themeColor = "#555555"
    bgImg = "images/kauotic_logo.png"
    homeSubtitle = "a club at Karlstad University about hacking, privacy and security"
    justifyContent = false
    relatedPosts = false

    [[params.social]]
    name = "discord"
    url = "https://discord.gg/s4a7GDafCb"

    [[params.social]]
    name = "twitter"
    url = "https://www.twitter.com/kauotic"

    [[params.social]]
    name = "github"
    url = "https://www.github.com/KAUotic"
    
    [[params.social]]
    name = "onion"
    url = "http://kauotic3fumvif4borgm2eg2w6fxtapo43o6adjvwwe5tqhpbewuc7id.onion"

    [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/groups/kauotic"

[menu]
    [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10
    [[menu.main]]
    name = "Groups"
    url = "groups/"
    weight = 10
    [[menu.main]]
    name = "Events"
    url = "events/"
    weight = 30
    [[menu.main]]
    name = "CTFd"
    url = "https://ctf.kauotic.se"
    weight = 40

[markup.goldmark.renderer]
    unsafe=true
